name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
  
  # - explicación: Iniciar sesión en Docker desde GIT
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  
  # - explicación: Construir las imágenes aplicando el parámetro NEW_VERSION anteriormente
  #definido (environment variable)
    - name: Build Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t zambrano1997/practica5:$NEW_VERSION .
        docker build -t zambrano1997/practica5:latest .
  
   # - explicación: Subir imagen al docker hub aplicando el parámetro NEW_VERSION
    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push zambrano1997/practica5:$NEW_VERSION
        docker push zambrano1997/practica5:latest
